# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "your-shopify-partner-app-api-key"
name = "your-shopify-partner-app-name"
handle = "your-shopify-partner-app-handle"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "muscled-production-app-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,read_publications,write_inventory,write_products,write_publications"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
