# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "your-shopify-partner-app-api-key"
name = "your app name"
handle = "your shopify partner app handle"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "example.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
